---
title: "Surface Biology and Geology 2025 Workshop: Advancing Capacity for SBG Data Users with Spaceborne and Airborne Precursor Data"
---

This workshop is part of an ongoing effort to build capacity within the Surface Biology and Geology (SBG) community by equipping users with knowledge, tools, and resources to effectively engage with precursor datasets and technologies. Specifically, it focuses on increasing awareness and utilization of airborne and spaceborne assets of opportunity such as EMIT, ECOSTRESS, and SBG-like airborne data and empowering users to develop scientific workflows and application-driven use cases that are relevant to the upcoming SBG mission.

The International Space Station is a critical asset for the Earth science community — both for advancing critical science and applications priorities, and as a platform for technology demonstrations/pathfinder missions. This is exemplified by the success of instruments like ECOSTRESS, a multispectral thermal radiometer, and EMIT, a visible to short wave infrared imaging spectrometer with best-in-class signal to noise. Operating at field-scale resolutions (<70 m), these instruments provide complementary datasets that enable rich analyses of surface processes and environmental change. With both sensors co-located on the ISS, we now have a unique opportunity to explore the synergistic value of combined thermal and imaging spectroscopy data. In addition to these spaceborne assets, airborne campaigns such as Surface Biology and Geology High-Frequency Time Series ([SHIFT](https://www.jpl.nasa.gov/news/california-field-campaign-helping-scientists-protect-diverse-ecosystems/)) are collecting high-resolution thermal and imaging spectroscopy data that are directly comparable to future SBG mission products. These datasets present valuable opportunities to prototype analyses, develop scalable workflows, and explore science and applications that can inform future SBG capabilities.

The overarching goal of this workshop is to engage and empower the SBG data user community by facilitating data discovery and access. A key focus will be demonstrating how to locate and work with concurrent EMIT and ECOSTRESS observations that align with existing airborne data, enabling participants to build integrated workflows and prepare for future SBG mission data.

This workshop is hosted by NASA [Land Processes Distributed Active Archive Center(LP DAAC)](https://www.earthdata.nasa.gov/centers/lp-daac) and [NASA Jet Propulsion Laboratory (JPL)](https://www.jpl.nasa.gov/) with support from the NASA [Openscapes](https://nasa-openscapes.github.io/) project. 
Hands-on exercises will be executed from a [Jupyter Hub on the Openscapes 2i2c cloud instance](https://workshop.openscapes.2i2c.cloud/). Enter your username and password  (`SBGTIM2025`) to login and select `14.8 GB RAM, upto 3.75 CPUs` Python Resource Allocation. 

<iframe src="https://docs.google.com/presentation/d/1Rg3Qgjh52Qcc8GJEWkiIVP9lGDJusH1P/embed?start=false&loop=false&delayms=3000" frameborder="0" width="750" height="445" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>


## Contact Info  

Email: <LPDAAC@usgs.gov>  
Voice: +1-866-573-3222  
Organization: Land Processes Distributed Active Archive Center (LP DAAC)¹  
Website: <https://www.earthdata.nasa.gov/centers/lp-daac>  

¹Work performed under USGS contract 140G0121D0001 for NASA contract NNG14HH33I.
