project:
  type: website
  output-dir: _site

execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website:
  page-navigation: true
  page-footer: 
    center: "VSWIR Imaging and Thermal Applications, Learning, and Science."

  title: "VITALS"
  site-url: https://nasa.github.io/VITALS/
  repo-url: https://github.com/nasa/VITALS/
  sidebar:
    logo: img/lp_jpl_vitals_light.png
    title: VITALS
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nasa.github.io/VITALS/
        text: "VITALS Website"
      - icon: github
        href: https://github.com/nasa/VITALS
        text: "VITALS Repository"
        
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - section: "Welcome"
        contents:
        - text: "Repository Description"
          href: index.qmd
      - section: "Workshops"
        contents:
        - text: "VSWIR-TIR Fundamentals"
          href: workshops/2025_VSWIR_TIR_Fundamentals.qmd
        - text: "2025 SBG Workshop"
          href: workshops/2025_sbg_workshop.qmd
        - text: "2024 SBG Workshop"
          href: workshops/2024_sbg_workshop.qmd
        - text: "2023 AGU Workshop"
          href: workshops/2023_agu_workshop.qmd
      - section: "Setup Instructions"
        contents:
        - text: "Prerequisites"
          href: setup/prerequisites.md
        - text: "Cloud Workspace Setup"
          href: setup/workshop_setup.qmd
        - text: "Local Python Environment Setup"
          href: setup/setup_instructions.md
      - section: "Python Notebooks"
        contents:
          - section: "EMIT & ECOSTRESS Tutorials"
            contents:
              - text: "1 Finding Concurrent Data"
                href: python/emit_ecostress/01_Finding_Concurrent_Data.ipynb
              - text: "2 EMIT Reflectance and ECOSTRESS LST"
                href: python/emit_ecostress/02_Working_with_EMIT_Reflectance_and_ECOSTRESS_LST.ipynb
              - text: "3 Canopy Water Content"
                href: python/emit_ecostress/03_EMIT_CWC_from_Reflectance.ipynb
              - text: "4 Dangermond Land Cover"
                href: python/emit_ecostress/04_Dangermond_Land_Cover.ipynb
              - text: "5 Santa Barbara Vineyards"
                href: python/emit_ecostress/05_SB_Vineyards.ipynb
          - section: "EMIT & NEON Tutorials"
            contents:
              - text: "1 Finding Co-located NEON EMIT Data"
                href: python/emit_neon/01_Finding_Co-located_NEON_EMIT_Data_NIWO.ipynb
              - text: "2 Exploring NEON and EMIT Reflectance Data"
                href: python/emit_neon/02_Exploring_NEON_and_EMIT_Reflectance_Data_NIWO.ipynb
          - section: "PACE & EMIT Tutorials"
            contents:
              - text: "1 Colocate PACE EMIT Data"
                href: python/emit_pace/01_Colocate_PACE_EMIT_Data.ipynb
              - text: "2 Process PACE EMIT Data"
                href: python/emit_pace/02_Process_PACE_EMIT_Data.ipynb
          - text: "Finding Coincident Airborne and Orbital Data"
            href: python/Finding_Coincident_Airborne_and_Orbital_Data.ipynb
          - text: "Exploring ECOSTRESS L2T LSTE"
            href: python/Exploring_ECOSTRESS_L2T_LSTE.ipynb
          - text: "Exploring EMIT L2A RFL"
            href: python/Exploring_EMIT_L2A_RFL.ipynb
          - text: "Exploring PACE OCI L2 SFRFL"
            href: python/Exploring_PACE_OCI_L2_SFRFL.ipynb
      - section: "Contributing"
        contents:
          - href: CONTRIBUTING.md
          - href: CODE_OF_CONDUCT.md
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo,theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true