name: lpdaac_vitals
channels:
  - conda-forge
dependencies:
  - cf_xarray
  - dask
  - earthaccess
  - fiona
  - gdal
  - geopandas
  - geoviews
  - h5netcdf
  - h5py
  - harmony-py
  - hvplot
  - ipykernel
  - jupyter
  - jupyter_bokeh
  - jupyterlab
  - libgdal-hdf4
  - neonutilities>=2.0.1
  - odc-stac
  - pip
  - pyresample
  - pystac-client
  - python=3.13
  - rasterio
  - ray-default
  - rioxarray
  - scikit-image
  - seaborn
  - spectral
  - pip:
      - "--editable ."
