[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "vitals"
dynamic = ["version"]
dependencies = [
    "earthaccess",
    "fsspec",
    "geopandas",
    "geoviews",
    "matplotlib",
    "netCDF4",
    "osgeo",
    "ray",
    "rioxarray",
    "scipy",
    "scikit-image",
    "spectral",
    "xarray",
]
